---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: arkonis-operator
    app.kubernetes.io/managed-by: kustomize
  name: arkonisdeployment-editor-role
rules:
- apiGroups:
  - arkonis.dev
  resources:
  - arkonisdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arkonis.dev
  resources:
  - arkonisdeployments/status
  verbs:
  - get
