---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: arkonis-operator
    app.kubernetes.io/managed-by: kustomize
  name: arkonisservice-viewer-role
rules:
- apiGroups:
  - arkonis.dev
  resources:
  - arkonisservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - arkonis.dev
  resources:
  - arkonisservices/status
  verbs:
  - get
