---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arkonis.dev
  resources:
  - agentconfigs
  - agentdeployments
  - agentmemories
  - agentpipelines
  - agentservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arkonis.dev
  resources:
  - agentconfigs/finalizers
  - agentdeployments/finalizers
  - agentmemories/finalizers
  - agentpipelines/finalizers
  - agentservices/finalizers
  verbs:
  - update
- apiGroups:
  - arkonis.dev
  resources:
  - agentconfigs/status
  - agentdeployments/status
  - agentmemories/status
  - agentpipelines/status
  - agentservices/status
  verbs:
  - get
  - patch
  - update
