---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arkonis.dev
  resources:
  - arkonisconfigs
  - arkonisdeployments
  - arkonismemories
  - arkonispipelines
  - arkonisservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arkonis.dev
  resources:
  - arkonisconfigs/finalizers
  - arkonisdeployments/finalizers
  - arkonismemories/finalizers
  - arkonispipelines/finalizers
  - arkonisservices/finalizers
  verbs:
  - update
- apiGroups:
  - arkonis.dev
  resources:
  - arkonisconfigs/status
  - arkonisdeployments/status
  - arkonismemories/status
  - arkonispipelines/status
  - arkonisservices/status
  verbs:
  - get
  - patch
  - update
