## Append samples of your project ##
resources:
- arkonis_v1alpha1_agentdeployment.yaml
- arkonis_v1alpha1_agentservice.yaml
- arkonis_v1alpha1_agentconfig.yaml
- arkonis_v1alpha1_agentpipeline.yaml
- arkonis_v1alpha1_agentmemory.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
