## Append samples of your project ##
resources:
- arkonis_v1alpha1_arkonisdeployment.yaml
- arkonis_v1alpha1_arkonisservice.yaml
- arkonis_v1alpha1_arkonisconfig.yaml
- arkonis_v1alpha1_arkonispipeline.yaml
- arkonis_v1alpha1_arkonismemory.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
